on: push

name: Experimental test build

jobs:

  build-release-artifacts:
    name: Build artifact
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - artifact: macos-x86_64
            os: macos-latest
            toolchain-suffix: x86_64-apple-darwin
            lib-file-name: librealearn.dylib
            target: x86_64-apple-darwin
            use-cross: false
            profile: debug
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.7 # This is relevant for macOS builds only (and only if not overridden).
    steps:
      # Prepare (all)
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.65.0-${{ matrix.toolchain-suffix }}
          target: ${{ matrix.target }}
          override: true
      - run: rustup component add rustfmt
      - run: brew install php
      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target }}
          use-cross: ${{ matrix.use-cross }}
      - name: Upload plug-in to artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          path: target/${{ matrix.target }}/${{ matrix.profile }}/${{ matrix.lib-file-name }}